class Commands:
    LEECH = "leech@LeechLiteBot"
    PURGE = "purge@LeechLiteBot"
    PAUSEALL = "pauseall@LeechLiteBot"
    RESUMEALL = "resumeall@LeechLiteBot"
    STATUS = "status@LeechLiteBot"
    SETTINGS = "settings@LeechLiteBot"
    EXEC = "exec@LeechLiteBot"
    UPLOAD = "upload@LeechLiteBot"
    YTDL = "ytdl@LeechLiteBot"
    PYTDL = "pytdl@LeechLiteBot"
    ABOUT = "about@LeechLiteBot"
    GETLOGS = "getlogs@LeechLiteBot"
    SERVER = "idiot@LeechLiteBot"
    USERSETTINGS = "usettings@LeechLiteBot"
    INSTADL = "instadl@LeechLiteBot"
