class Commands:
    LEECH = "leech@FlixTubeRobot"
    PURGE = "purge@FlixTubeRobot"
    PAUSEALL = "pauseall@FlixTubeRobot"
    RESUMEALL = "resumeall@FlixTubeRobot"
    STATUS = "status@FlixTubeRobot"
    SETTINGS = "settings@FlixTubeRobot"
    EXEC = "exec@FlixTubeRobot"
    UPLOAD = "upload@FlixTubeRobot"
    YTDL = "ytdl@FlixTubeRobot"
    PYTDL = "pytdl@FlixTubeRobot"
    ABOUT = "about@FlixTubeRobot"
    GETLOGS = "getlogs@FlixTubeRobot"
    SERVER = "server@FlixTubeRobot"
    USERSETTINGS = "usetting@FlixTubeRobot"
    INSTADL = "instadl@FlixTubeRobot"
