class Commands:
    LEECH = "leech@TorToolKitFlixBot"
    PURGE = "purge@TorToolKitFlixBot"
    PAUSEALL = "pauseall@TorToolKitFlixBot"
    RESUMEALL = "resumeall@TorToolKitFlixBot"
    STATUS = "status@TorToolKitFlixBot"
    SETTINGS = "settings@TorToolKitFlixBot"
    EXEC = "exec@TorToolKitFlixBot"
    UPLOAD = "upload@TorToolKitFlixBot"
    YTDL = "ytdl@TorToolKitFlixBot"
    PYTDL = "pytdl@TorToolKitFlixBot"
    ABOUT = "about@TorToolKitFlixBot"
    GETLOGS = "getlogs@TorToolKitFlixBot"
    SERVER = "server@TorToolKitFlixBot"
    USERSETTINGS = "usetting@TorToolKitFlixBot"
    INSTADL = "instadl@TorToolKitFlixBot"
